name: example
description: An example Flutter project to demonstrate the usage of cached_build_runner.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  sync: ^0.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  cached_build_runner:
    path: ../

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

