name: cached_build_runner
description: Optimizes the build_runner by caching generated codes for non changed .dart files
version: 0.1.0-pre2
homepage: https://github.com/jyotirmoy-paul/cached_build_runner
maintainer: Jyotirmoy Paul (@jyotirmoy-paul)

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.2
  args: ^2.4.0
  barbecue: ^0.5.0
  crypto: ^3.0.1
  get_it: ^7.6.7
  hive: ^2.2.3
  logger: ^1.1.0
  path: ^1.8.2
  synchronized: ^3.0.1
  text_table: ^4.0.3

dev_dependencies:
  netglade_analysis: ^7.0.0
